require('telescope').load_extension('dap')
require('dbg.python')
require('dbg.go')

vim.api.nvim_set_keymap('n', '<leader>ds', '<cmd>lua require"dap".stop()<CR>', {})
vim.api.nvim_set_keymap('n', '<leader>dn', '<cmd>lua require"dap".continue()<CR>', {})
vim.api.nvim_set_keymap('n', '<leader>dk', '<cmd>lua require"dap".up()<CR>', {})
vim.api.nvim_set_keymap('n', '<leader>dc', '<cmd>lua require"dap".down()<CR>', {})
vim.api.nvim_set_keymap('n', '<leader>d_', '<cmd>lua require"dap".repl.run_last()<CR>', {})
vim.api.nvim_set_keymap('n', '<leader>di', '<cmd>lua require"dap.ui.widgets".hover()<CR>', {})
vim.api.nvim_set_keymap('v', '<leader>di', '<cmd>lua require"dap.ui.variables".visual_hover()<CR>', {})
vim.api.nvim_set_keymap('n', '<leader>d?', '<cmd>lua local widgets=require"dap.ui.widgets";widgets.centered_float(widgets.scope)<CR>', {})
vim.api.nvim_set_keymap('n', '<S-j>', '<cmd>lua require"dap".step_over()<CR>', {})
vim.api.nvim_set_keymap('n', '<S-l>', '<cmd>lua require"dap".step_into()<CR>', {})
vim.api.nvim_set_keymap('n', '<S-k>', '<cmd>lua require"dap".step_out()<CR>', {})
vim.api.nvim_set_keymap('n', '<leader>dh', '<cmd>lua require"dap".toggle_breakpoint()<CR>', {})
vim.api.nvim_set_keymap('n', '<leader>de', '<cmd>lua require"dap".set_execption_breakpoints({"all"})<CR>', {})
vim.api.nvim_set_keymap('n', '<leader>dsc', '<cmd>lua require"dap".set_breakpoint(vim.fn.input("Breakpoint condition: "))<CR>', {})
vim.api.nvim_set_keymap('n', '<leader>dsm', '<cmd>lua require"dap".set_breakpoint(nil, nil, vim.fn.input("Log point message: "))<CR>', {})
vim.api.nvim_set_keymap('n', '<leader>dr', '<cmd>lua require"dap".repl.open()<CR>', {})

-- telescope-dap
vim.api.nvim_set_keymap('n', '<leader>dcc', '<cmd>lua require"telescope".extensions.dap.commands{}<CR>', {})
vim.api.nvim_set_keymap('n', '<leader>dco', '<cmd>lua require"telescope".extensions.dap.configurations{}<CR>', {})
vim.api.nvim_set_keymap('n', '<leader>dlb', '<cmd>lua require"telescope".extensions.dap.list_breakpoints{}<CR>', {})
vim.api.nvim_set_keymap('n', '<leader>dv', '<cmd>lua require"telescope".extensions.dap.variables{}<CR>', {})
vim.api.nvim_set_keymap('n', '<leader>df', '<cmd>lua require"telescope".extensions.dap.frames{}<CR>', {})
 
